; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for :
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_shatterhand:=music_data_shatterhand

music_data_shatterhand:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : shatterhand
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 266,221

.export music_data_shatterhand
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env10,@env14,@env0 ; 00 : Blank
	.word @env23,@env15,@env14,@env0 ; 01 : Kick Tri Cut
	.word @env22,@env5,@env14,@env0 ; 02 : Hat Closed
	.word @env19,@env26,@env14,@env0 ; 03 : Snare Noise
	.word @env2,@env21,@env14,@env0 ; 04 : Kick Noise
	.word @env23,@env24,@env14,@env0 ; 05 : KickSnare Tri
	.word @env6,@env4,@env8,@env0 ; 06 : Arp Hyper Major 5
	.word @env27,@env11,@env14,@env0 ; 07 : Kick Noise Open
	.word @env1,@env5,@env14,@env0 ; 08 : Hat Open
	.word @env6,@env12,@env8,@env0 ; 09 : New instrument 1
	.word @env6,@env3,@env8,@env0 ; 0a : Arp Hyper Major 3
	.word @env6,@env7,@env8,@env0 ; 0b : Arp Hyper Minor 3
	.word @env6,@env17,@env8,@env0 ; 0c : Arp Hyper Major
	.word @env13,@env16,@env25,@env0 ; 0d : Lead Arp Pluck
	.word @env9,@env18,@env14,@env0 ; 0e : Snare Tri Cut
	.word @env6,@env20,@env14,@env0 ; 0f : Crash

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c6,$c4,$03,$c3,$03,$c2,$03,$c1,$00,$08
@env2:
	.byte $00,$c5,$c3,$c2,$c1,$00,$04
@env3:
	.byte $b8,$bb,$c0,$c4,$c7,$cc,$00,$00
@env4:
	.byte $bb,$c0,$c4,$c7,$cc,$d0,$00,$00
@env5:
	.byte $cd,$ce,$00,$01
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $c0,$c3,$c7,$cc,$cf,$d3,$00,$00
@env8:
	.byte $c2,$07,$c1,$07,$c0,$07,$c1,$06,$c1,$00,$00
@env9:
	.byte $00,$cf,$02,$c0,$00,$03
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $c9,$cf,$cb,$00,$02
@env12:
	.byte $bb,$c0,$c2,$c7,$cc,$ce,$00,$00
@env13:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$00,$06
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $c0,$be,$bb,$b6,$b4,$b2,$00,$05
@env16:
	.byte $cc,$cc,$c0,$00,$02
@env17:
	.byte $c0,$c4,$c7,$cc,$d0,$d3,$00,$00
@env18:
	.byte $c9,$c7,$c5,$00,$02
@env19:
	.byte $00,$c7,$c4,$03,$c3,$03,$c2,$03,$c1,$03,$c0,$00,$0a
@env20:
	.byte $c9,$cb,$00,$01
@env21:
	.byte $c9,$cf,$00,$01
@env22:
	.byte $00,$c6,$c4,$c3,$c2,$c1,$c0,$00,$06
@env23:
	.byte $00,$cf,$05,$c0,$00,$03
@env24:
	.byte $c9,$c7,$c5,$b6,$b4,$b2,$00,$05
@env25:
	.byte $c2,$c2,$c1,$00,$02
@env26:
	.byte $c9,$02,$ca,$00,$02
@env27:
	.byte $00,$c5,$c3,$c2,$00,$03

@samples:

@song0ch0:
	.byte $46, $03
@song0ch0loop:
	.byte $00, $83, $73, $4e, $01, $9a, $20, $85, $1d, $85, $1d, $85, $1b, $85, $19
@song0ref19:
	.byte $71, $4e, $00, $94, $1e
@song0ref24:
	.byte $81, $72, $83
@song0ref27:
	.byte $75, $81
@song0ref29:
	.byte $74, $81, $73, $81, $72, $81, $71, $83, $72, $83, $75, $81, $74, $81, $73, $81, $72, $81, $71, $83, $72, $83, $75, $81
	.byte $74, $81, $73, $81, $72, $81, $71, $83, $72, $83, $75, $8c, $19
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $71, $4e, $00, $96, $16
	.byte $41, $14
	.word @song0ref24
	.byte $75, $98, $14
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $41, $16
	.word @song0ref19
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $71, $4e, $00, $96, $16
	.byte $41, $14
	.word @song0ref24
	.byte $75, $98, $14
	.byte $41, $0f
	.word @song0ref29
	.byte $73, $4e, $ff, $4f, $02, $80, $27, $85, $2c, $85, $30, $85, $31, $85
	.byte $41, $16
	.word @song0ref19
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $71, $4e, $00, $96, $16
	.byte $41, $14
	.word @song0ref24
	.byte $75, $98, $14
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $41, $16
	.word @song0ref19
	.byte $41, $11
	.word @song0ref29
	.byte $41, $0a
	.word @song0ref27
	.byte $71, $4e, $00, $96, $16
	.byte $41, $14
	.word @song0ref24
	.byte $75, $98, $14, $74, $81, $73, $81, $72, $81, $bf, $75, $8c, $19, $81, $72, $83, $75, $92, $19, $81, $72, $83, $74, $8c
	.byte $19, $81, $72, $83, $74, $92, $19, $81, $72, $83, $73, $8c, $19, $81, $71, $83, $73, $92, $19, $81, $71, $83, $72, $8c
	.byte $19, $81, $71, $83, $72, $92, $19, $81, $71, $83, $8c, $19, $81, $70, $83, $71, $92, $19, $81, $70, $b3, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $79, $9a, $20, $83, $73, $20
@song0ref248:
	.byte $79, $1d, $83, $73, $20, $79, $1d, $83, $73, $1d
@song0ref258:
	.byte $79, $1b, $83, $73, $1d, $79, $19, $83, $73, $1b, $79, $16, $85, $73, $19, $85, $79, $19, $85, $73, $16, $85, $79, $16
	.byte $85, $73, $19, $81, $79, $19, $85, $73, $16, $81, $79, $1d, $85, $73, $19, $81, $1d, $81
@song0ref300:
	.byte $79, $14, $85, $73, $1d, $81, $14, $81, $79, $20, $83, $73, $14
	.byte $41, $1c
	.word @song0ref248
	.byte $79, $1b, $85, $73, $19
@song0ref321:
	.byte $81, $1b, $81, $79, $14, $85, $73, $1b, $81, $14, $81, $79, $20, $83, $73, $14, $79, $1e, $83, $73, $20, $79, $1d, $83
	.byte $73, $1e
	.byte $41, $09
	.word @song0ref258
@song0ref350:
	.byte $81, $16, $81, $79, $19, $85, $73, $16, $81, $19, $81, $79, $16, $85, $73, $19, $81, $79, $14, $85, $73, $16, $81, $79
	.byte $1c, $1d, $83, $73, $14, $83, $1d
	.byte $41, $09
	.word @song0ref300
	.byte $41, $0e
	.word @song0ref248
	.byte $73, $1b
	.byte $41, $09
	.word @song0ref350
	.byte $79, $20, $83, $73, $19, $79, $1e, $81, $1d, $85, $73, $1e, $81, $79, $1b, $85, $73, $1d
	.byte $41, $0c
	.word @song0ref321
	.byte $79, $1b, $83, $73, $20, $79, $20, $83, $73, $1b, $79, $24, $83, $73, $20, $79, $25, $83, $73, $24, $79, $19, $85, $73
	.byte $25
@song0ref438:
	.byte $81, $19, $81, $79, $19, $85, $73, $19, $85, $79, $19, $85, $73, $19, $81, $79, $18, $19, $83, $73, $18, $19, $79, $14
	.byte $85, $73, $19, $81, $14, $81
@song0ref468:
	.byte $79, $14, $83, $73, $14
@song0ref473:
	.byte $79, $19, $83, $73, $14, $79, $1b, $83, $73, $19, $79, $1d, $83, $73, $1b, $79, $1d, $83, $73, $1d, $79, $1b, $83, $73
	.byte $1d, $79, $1b, $83, $73, $1b, $79, $19, $85, $73, $1b
	.byte $41, $0b
	.word @song0ref438
@song0ref511:
	.byte $79, $1d, $85, $73, $19, $81, $79, $1b, $85, $73, $1d, $81, $1b, $81, $79, $14, $83, $73, $1b
	.byte $41, $0c
	.word @song0ref473
	.byte $79, $22, $83, $73, $1d, $79, $22, $83, $73, $22, $79, $19, $85, $73, $22
	.byte $41, $0b
	.word @song0ref438
	.byte $79, $14, $85, $73, $19, $81, $79, $14, $85, $73, $14, $85
	.byte $41, $18
	.word @song0ref468
	.byte $41, $0b
	.word @song0ref438
	.byte $41, $09
	.word @song0ref511
	.byte $89, $79, $19, $85, $73, $1b, $81, $19, $81, $79, $1b, $85, $20, $85, $73, $1b, $81, $20, $81, $79, $19, $85, $73, $87
	.byte $75, $19, $85, $71, $87, $73, $19, $85, $71, $87, $72, $19, $85, $71, $87, $19, $85, $00, $bd, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $85, $9c, $19, $81, $19, $81, $19, $85, $19, $81, $19, $81, $19
@song0ref633:
	.byte $85, $82
@song0ref635:
	.byte $19, $85, $80, $12, $85, $82, $19, $85, $80, $12, $85, $82, $19, $85, $80, $12
@song0ref651:
	.byte $85, $82, $19, $85, $80, $19, $85, $82, $19, $85, $80, $19
	.byte $41, $08
	.word @song0ref651
@song0ref666:
	.byte $85, $82
@song0ref668:
	.byte $19, $85, $80, $19, $85, $82
@song0ref674:
	.byte $19, $85, $80, $16, $85, $82, $19, $85, $80, $16, $85, $82, $19, $85, $80, $16
@song0ref690:
	.byte $85, $82, $19, $85, $80, $14, $85, $82, $19, $85, $80, $14
	.byte $41, $08
	.word @song0ref690
	.byte $85, $82, $19, $85, $80, $14
	.byte $41, $14
	.word @song0ref633
	.byte $41, $08
	.word @song0ref651
	.byte $41, $18
	.word @song0ref666
	.byte $85, $82, $19, $85, $80, $14, $85, $9c, $19, $8d, $19, $85, $82, $19, $19, $19, $81, $19, $85, $80, $12, $85, $8a
	.byte $41, $08
	.word @song0ref635
@song0ref746:
	.byte $8a, $19, $85, $80, $19, $85, $82, $19, $85, $80, $19, $85
	.byte $41, $08
	.word @song0ref746
	.byte $8a
	.byte $41, $08
	.word @song0ref668
	.byte $8a
	.byte $41, $08
	.word @song0ref674
@song0ref769:
	.byte $8a, $19, $85, $80, $14, $85, $82, $19, $85, $80, $14, $85
	.byte $41, $08
	.word @song0ref769
	.byte $8a, $19, $85, $80, $14, $85, $82, $19, $85, $80, $12, $85, $8a
	.byte $41, $08
	.word @song0ref635
	.byte $41, $08
	.word @song0ref746
	.byte $41, $08
	.word @song0ref746
	.byte $8a
	.byte $41, $08
	.word @song0ref668
	.byte $8a
	.byte $41, $08
	.word @song0ref674
	.byte $8a, $19, $85, $80, $14, $85, $82, $19, $b5, $19, $80, $0d, $83, $9f, $00, $dd, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $00, $85, $7a, $86, $21, $81, $7b, $21, $81, $7c, $22, $85, $7d, $23, $81, $7e, $23, $81, $7f, $14, $85, $8e, $14, $74
	.byte $80, $1f, $8b, $7f, $8e, $14, $74, $80, $1f, $8b, $7f, $8e, $14, $73, $80, $1f, $8b, $7f, $8e, $14, $73, $80, $1f, $8b
	.byte $7f, $8e, $14, $72, $80, $1f, $8b, $7f, $8e, $14, $72, $80, $1f, $8b, $7f, $8e, $14, $71, $80, $1f, $8b, $7f, $8e, $14
	.byte $71, $80, $1f, $8b, $7f, $88
@song0ref912:
	.byte $14, $8d, $14, $8d, $14, $8d, $14, $8d
	.byte $41, $08
	.word @song0ref912
	.byte $41, $08
	.word @song0ref912
	.byte $41, $08
	.word @song0ref912
	.byte $41, $08
	.word @song0ref912
	.byte $14, $8d, $14, $8d, $7e, $86, $23, $8d, $7f, $14, $85, $88, $14, $14, $14, $81, $77, $9e, $14, $75, $85, $74, $87, $7f
	.byte $86, $14, $81, $73, $80, $1f, $89, $7f, $8e, $14, $72, $80, $1f, $83, $7f
@song0ref971:
	.byte $90, $14, $85, $86, $14, $85, $90, $14, $85, $88, $14, $85
	.byte $41, $08
	.word @song0ref971
	.byte $90, $14, $85, $86, $14, $85, $90
@song0ref993:
	.byte $14, $85, $88, $14, $81, $78, $84, $14, $81, $7f, $14, $85, $86, $14, $85, $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84
	.byte $41, $0a
	.word @song0ref993
	.byte $84, $14, $85, $88, $14, $bd, $8f, $78, $86, $14, $8d, $74, $14, $85, $00, $85, $72, $14, $81, $00, $89, $71, $14, $00
	.byte $bb, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $a7, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch4loop
